[features]
resolution = true
skip-lint = false

[programs.devnet]
crowdfunding = "GQvtH9oJoWXwr5Q9WrbVAipYqfJb2JiLjB6iKYurynEr"

[deploy]
crowdfunding = "target/deploy/crowdfunding-keypair.json"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "ts-node scripts/initialize.ts"
create_campaign = "ts-node scripts/create_campaign.ts"
donate = "ts-node scripts/donate.ts"
get_campaigns = "ts-node scripts/get_campaigns.ts"
withdraw = "ts-node scripts/withdraw.ts"
check-campaign = "ts-node scripts/check_campaign.ts"

